FROM golang:1.18.5-alpine3.15 as builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 go build -a -ldflags "-w -s" -o url-shorting-service ./cmd/main.go

FROM alpine
WORKDIR /app 
COPY --from=builder /app/url-shorting-service .
COPY .env .
COPY static static
EXPOSE "${API_PORT}" "${API_PORT}"
CMD [ "./url-shorting-service" ]