version: "3.9"
services:
  url-shorting-service:
      restart: on-failure:5
      build:
        context: .
        dockerfile: Dockerfile.scratch
      env_file: .env
      depends_on:
        - pgsql
      ports:
        - "8080:8080"
  pgsql:
    image: postgres:latest
    restart: on-failure:5
    volumes:
    - data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "${PG_PORT}:${PG_PORT}"
    command: -p "${PG_PORT}"
volumes:
  data:

